import Head from "next/head";
import Link from "next/link";

export default function PageLayout({
  children,
  title = "App",
  display = "block",
}) {
  return (
    <div>
      <Head>
        {/* ACÁ SE MODIFCA EL HEAD DEL HTML */}
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav style={{ display: `${display}` }}>
        <ul>
          <Link href={"/"}>Home</Link>
          <Link href={"/login"}>Login</Link>
          <Link href={"/articles/news"}>News</Link>
          <Link href={"/signin"}>Sign In</Link>
        </ul>
      </nav>
      <main>{children}</main>
      <style jsx>
        {`
          nav {
            height: 10vh;
            background: grey;
          }
        `}
      </style>
    </div>
  );
}
